# Generated by Django 2.0.4 on 2018-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'CommentLike', 'verbose_name_plural': 'Comment likes'},
        ),
        migrations.AlterModelOptions(
            name='reviewlike',
            options={'verbose_name': 'ReviewLike', 'verbose_name_plural': 'Review likes'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='feed.Category'),
        ),
    ]
