# Generated by Django 2.0.4 on 2018-05-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180430_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewlike',
            options={'verbose_name': 'Review like', 'verbose_name_plural': 'Review likes'},
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
